// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-QkXRKq6wlXMY6TUxItM59-1vKtZDRsM',
    appId: '1:557450296752:web:59a3b06cbbed0d5a4e6a75',
    messagingSenderId: '557450296752',
    projectId: 'habio-35e46',
    authDomain: 'habio-35e46.firebaseapp.com',
    storageBucket: 'habio-35e46.appspot.com',
    measurementId: 'G-NRK7C491Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-YrcDbZK81ePVy9zoGIh9wsbdewaLnbU',
    appId: '1:557450296752:android:956783250bbfc0674e6a75',
    messagingSenderId: '557450296752',
    projectId: 'habio-35e46',
    storageBucket: 'habio-35e46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPY87q6YluHPFsdM4p1uwL02b6O5wQ2DU',
    appId: '1:557450296752:ios:e317ca104fe8806f4e6a75',
    messagingSenderId: '557450296752',
    projectId: 'habio-35e46',
    storageBucket: 'habio-35e46.appspot.com',
    iosBundleId: 'com.example.perHabit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-QkXRKq6wlXMY6TUxItM59-1vKtZDRsM',
    appId: '1:557450296752:web:9c17ecd8b71b1ab14e6a75',
    messagingSenderId: '557450296752',
    projectId: 'habio-35e46',
    authDomain: 'habio-35e46.firebaseapp.com',
    storageBucket: 'habio-35e46.appspot.com',
    measurementId: 'G-2DCT21WXRV',
  );

}